{ lib }:

# Pure renderer for MANUAL-<host>.md (unit-tested by tests/manual-render.py).
# Steps are grouped by phase, then sorted by owner and id, so the same step
# always lands in the same place on every host that declares it.
{
  host,
  rev,
  bootstrap,
  docs,
  steps,
}:
let
  headings = {
    "after-switch" = "## After the first switch";
    snapshot = "## Snapshots (the list IS the declaration)";
  };
  ordered =
    phase:
    lib.sort (a: b: a.owner < b.owner || (a.owner == b.owner && a.id < b.id)) (
      lib.mapAttrsToList (id: s: s // { inherit id; }) (lib.filterAttrs (_: s: s.phase == phase) steps)
    );
  renderStep =
    s:
    ''
      ### ${s.title} (${s.owner} · ${if s.desktop then "desktop" else "shell"})

      ${lib.removeSuffix "\n" s.body}
    ''
    + lib.optionalString (s.verify != null) "\nVerify: `${s.verify}`\n"
    + lib.optionalString (s.redo != null) "\nRedo: ${s.redo}\n";
  section =
    phase:
    lib.optionalString (ordered phase != [ ]) ''
      ${headings.${phase}}

      ${lib.concatMapStringsSep "\n" renderStep (ordered phase)}
    '';
in
''
  <!-- GENERATED by `just manual` from https://github.com/alexjmiller5/nix-config/commit/${rev} - edit the declaring nix module or docs/manual/${host}-bootstrap.md, then rerun. -->
  # MANUAL-${host}.md - steps nix cannot do

  Rendered from `manual.steps` (modules/manual-steps.nix); the bootstrap
  section is docs/manual/${host}-bootstrap.md. `manual-check` on the machine
  reports which verifiable steps are still owed.

  ${lib.removeSuffix "\n" bootstrap}

  ${section "after-switch"}${section "snapshot"}## Reference

  ${lib.concatMapStringsSep "\n" (d: "- [${d}](${d})") docs}
''
