#!/usr/bin/env python3
"""Render a fixture host's manual and assert shape, ordering and host scoping."""
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
expression = r'''
let
  flake = builtins.getFlake ROOT;
  pkgs = flake.inputs.nixpkgs.legacyPackages.aarch64-darwin;
  lib = pkgs.lib;
  render = import (ROOT + "/modules/manual-render.nix") { inherit lib; };
  steps = {
    zeta = { title = "Zeta"; owner = "b-owner"; phase = "after-switch"; desktop = true;
             body = "do zeta"; verify = "true"; redo = "after z"; };
    alpha = { title = "Alpha"; owner = "a-owner"; phase = "after-switch"; desktop = false;
              body = "do alpha"; verify = null; redo = null; };
    snap = { title = "Snap"; owner = "a-owner"; phase = "snapshot"; desktop = false;
             body = "the list"; verify = null; redo = null; };
  };
in render { host = "fixture"; rev = "abc123"; bootstrap = "## Boot\nfirst\n"; docs = [ "docs/x.md" ]; inherit steps; }
'''.replace("ROOT", json.dumps(str(ROOT)))
r = subprocess.run(["nix", "eval", "--impure", "--raw", "--expr", expression], text=True, capture_output=True)
assert r.returncode == 0, r.stderr
out = r.stdout
lines = out.splitlines()
assert lines[0] == (
    "<!-- GENERATED by `just manual` from https://github.com/alexjmiller5/nix-config/commit/abc123"
    " - edit the declaring nix module or docs/manual/fixture-bootstrap.md, then rerun. -->"
), lines[0]
assert "# MANUAL-fixture.md" in out
assert out.index("## Boot") < out.index("## After the first switch") < out.index("## Snapshots")
assert out.index("### Alpha") < out.index("### Zeta") < out.index("### Snap"), "phase, owner, id ordering"
assert "### Zeta (b-owner · desktop)" in out and "### Alpha (a-owner · shell)" in out
assert "Verify: `true`" in out and "Redo: after z" in out
assert out.count("Verify:") == 1 and out.count("Redo:") == 1
assert "## Reference" in out and "[docs/x.md](docs/x.md)" in out
print("manual-render OK")
